### ISSUE TITLE
Document comment-based schema discovery

### ISSUE THREAD

**Issue by Profpatsch** [tamasfe/taplo#117] opened 2021-06-02 15:30 UTC
I was trying to debug why my workspace configuration wasn’t triggering the schema file for a file I opened.
Then I noticed that taplo has a “hidden feature” to discover the schema from the config file, which makes things so much easier to understand and debug:

https://github.com/tamasfe/taplo/blob/5681a56ac51c4b518f1131a43ec2c6fba893bf5c/taplo/src/analytics.rs#L573-L594

So adding a line like

```
#:schema ./vendor/schema-lib/project.toml.schema.json
```

will make it “just work”. 

I re-read the documentation, but I couldn’t find any reference to this feature.
I would have expected it to be under https://taplo.tamasfe.dev/configuration/#schema

**Comment by Profpatsch** [comment] 2021-06-02 15:31
The actual part where the schema link is parsed is 

https://github.com/tamasfe/taplo/blob/5681a56ac51c4b518f1131a43ec2c6fba893bf5c/taplo-lsp/src/lib.rs#L119-L130

**Comment by tamasfe** [comment] 2021-06-02 21:29
Thank you, this should be a duplicate of #97. It's not yet documented, as it's not really a thought-out feature.

**Closed by tamasfe** 2021-06-02 21:29 UTC
