### ISSUE TITLE
Passing `--locked` to `cargo install` causes  error[E0635]: unknown feature `proc_macro_span_shrink`

### ISSUE THREAD

**Issue by yonas** [tamasfe/taplo#518] opened 2023-12-16 04:42 UTC
Not a problem with plain `cargo install taplo`.

```
$  cargo install taplo-cli --locked
...
   Compiling futures-sink v0.3.25
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /home/yonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.47/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^

   Compiling tinyvec_macros v0.1.0
   Compiling futures-task v0.3.25
   Compiling futures-channel v0.3.25
   Compiling tinyvec v1.6.0
   Compiling ahash v0.7.6
   Compiling memoffset v0.6.5
   Compiling crossbeam-epoch v0.9.11
   Compiling rayon v1.5.3
   Compiling indexmap v1.9.1
   Compiling lock_api v0.4.9
For more information about this error, try `rustc --explain E0635`.
error: could not compile `proc-macro2` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `taplo-cli v0.8.1`, intermediate artifacts can be found at `/tmp/cargo-install2O0F47`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

OS: `FreeBSD 14`

**Comment by ia0** [comment] 2023-12-16 08:45
This looks like a duplicate of #507, itself a duplicate of #490, both waiting for #473.

**Closed by ia0** 2023-12-16 08:45 UTC
