### ISSUE TITLE
VSCode plugin: Auto-indentation for table entries breaks in some cases

### ISSUE THREAD

**Issue by rsnk96** [tamasfe/taplo#503] opened 2023-11-03 15:05 UTC
I have configured auto-indentation for my VS Code workspace. The following are the settings in my VS Code:
```json
{
    "evenBetterToml.formatter.columnWidth": 119,
    "evenBetterToml.formatter.alignComments": true,
    "evenBetterToml.formatter.arrayAutoCollapse": true,
    "evenBetterToml.formatter.indentEntries": true,
    "evenBetterToml.formatter.indentTables": true,
}
```

The auto-formatting works well if the keys of a table are sequentially getting further and further nested. However, when a new key at a parent level of nesting is then introduced, it breaks the nested structure, as pictured below
![image](https://github.com/tamasfe/taplo/assets/10851575/00a9a695-1251-4d52-9c21-a12d4166cd80)

Would appreciate any assistance on how I can fix this, or contribute a PR to this repo that should fix it

**Comment by ia0** [comment] 2023-11-03 16:19
Thanks for the report! This is a duplicate of #438 and should have been fixed by #450. On the next release, it should be fixed.

**Closed by ia0** 2023-11-03 16:19 UTC
