### ISSUE TITLE
Latest CLI release doesn't contain build assets

### ISSUE THREAD

**Issue by uncenter** [tamasfe/taplo#552] opened 2024-02-13 04:13 UTC
Up through [Taplo CLI 0.8.1](https://github.com/tamasfe/taplo/releases/tag/0.8.1), build assets for each platform and architecture were available from each release:

![image](https://github.com/tamasfe/taplo/assets/47499684/5368f994-3047-4a57-9239-a2489d4242ec)

However, the latest release - https://github.com/tamasfe/taplo/releases/tag/release-taplo-cli-0.9.0 - lacks these assets. It looks like the releases are now being created by @JounQin rather than by the CI.

**Comment by JounQin** [comment] 2024-02-13 04:31
Duplicate of #542

**Comment by JounQin** [comment] 2024-02-13 04:32
Please search before creating new issue.

**Closed** 2024-02-13 04:32 UTC

**Comment by uncenter** [comment] 2024-02-13 04:36
Gotcha. Assumed the assets would have been reuploaded by now, my bad.
