### ISSUE TITLE
RuntimeError: unreachable

### ISSUE THREAD

**Issue by otavio-silva** [tamasfe/taplo#504] opened 2023-11-14 18:49 UTC
# Description
Installing in VSCodium and opening a `.toml` file gives error that the LSP crashed 5 times in the last 3 minutes.

# Console output
Pastebin link because GitHub complains it's too long: [https://pastebin.com/uWcP00PW](https://pastebin.com/uWcP00PW)
# VSCodium info
Version: 1.83.1
Release: 23285
Commit: 36d13de33ac0d6c684f10f99cff352e2f58228b3
Date: 2023-10-12T18:42:10.077Z
Electron: 25.8.4
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by ia0** [comment] 2023-11-14 19:13
This looks like a duplicate of #434 which is fixed by #462 which is waiting to be released by #473. Feel free to subscribe to that last issue to know when your issue will be fixed.

**Closed by ia0** 2023-11-14 19:13 UTC

**Comment by otavio-silva** [comment] 2023-11-14 19:19
> This looks like a duplicate of #434 which is fixed by #462 which is waiting to be released by #473. Feel free to subscribe to that last issue to know when your issue will be fixed.


I see, glad it's been addressed. Wouldn't a tag like `awaiting-new-release` more appropriate?
