### ISSUE TITLE
LSP doesn't seem to work with local file as documented

### ISSUE THREAD

**Issue by Salamandar** [tamasfe/taplo#377] opened 2023-02-02 12:41 UTC
I tried using the VScode extension to develop my schema file, with this in my TOML file:
```
#:schema ./testschema.json
```
and no linter errors were shown (although my toml file is invalid).

What worked though is this
```
#:schema file://./yunohost_manifest_schema.json
```

This is not as documented here: https://taplo.tamasfe.dev/configuration/directives.html

**Comment by sethp** [comment] 2023-02-03 18:14
I ran into a similar issue, though at least in my case it turned out to be #347 : the extension would only report schema failures ten minutes or so after the first load (or if I manually busted the cache with `rg foo-schema.json -l0 ~/.config/Code/User/globalStorage/ | xargs -r0 rm`). After that, the relative path worked (though, it was again validating against the same schema for the next 10 minutes).

In your case, is it possible that switching to `file://...` simply side-stepped the cache by using a new path, do you think?

**Comment by Salamandar** [comment] 2023-02-08 09:30
I tried using `file://`, it works when using VSCode, but not when manually invoking taplo…
```
ERROR taplo:lint_files: invalid file error=failed to load schema file://../apps_repo/schemas/manifest.schema.json path="/home/felix/tmp/Yunohost/apps/cinny_ynh/manifest.toml"
```

**Comment by davidtorosyan** [comment] 2023-07-31 03:58
I hit this too, but in my case clearing the cache with the built-in command didn't work, I had to delete the `Code/User/globalStorage/tamasfe.even-better-toml` folder.

Even then, all it did was remove the stale warnings I was getting. Now I'm unable to validate against local files at all.

**Comment by sethp** [comment] 2023-08-01 15:04
@davidtorosyan I don't see anything obvious in the cache code that'll re-create that directory if it's been deleted; at a guess you're getting as far as [write_file](https://github.com/tamasfe/taplo/blob/73494e610153c21e5d92ed271e7de00d1c108036/crates/taplo-common/src/schema/cache.rs#L102) before bailing out with an error. I'd suggest either re-creating that directory, or figuring out who created it in the first place (something in the vscode plugin infrastructure, perhaps?) and getting that to re-trigger.

The issue here is actually #347: my suggested workaround above to cache bust by switching to an equivalent URL only really works once (or, as many times as you're willing to make symlinks, i guess). The discussion over there covers more effective solutions: automatic cache busting, disabling a filesystem-local-cache for a filesystem-local-file, etc.

**Comment by ia0** [comment] 2023-08-08 13:45
Should this be marked as a duplicate of #347?

**Closed** 2023-12-02 18:29 UTC
