### ISSUE TITLE
Formatter error with invalid escape sequence

### ISSUE THREAD

**Issue by sun128764** [tamasfe/taplo#461] opened 2023-08-18 09:18 UTC
I have a toml file with this part

> [[Contents]]
Sid = 2073540
Path = "T:\en"
Title ="some string"

Obviously \e is an invalid escape sequence. Then the formatter will do like this

> [[Contents]]
Path = "T:\en"Sid = 2073540
Title = "some string"

Here's another example

> [[Contents]]
Path = "T:\en"
Title ="BlueLock"
ScriptRegex = "\.pdf"

> [[Contents]]
Path = "T:\en"
ScriptRegex = "\.pdf"Title = "BlueLock"

**Comment by ia0** [comment] 2023-08-18 22:10
Thanks for the bug report! I am able to reproduce and this is a good example that LSP should not format in case of errors. I'm closing as a duplicate of #446 and will follow up there.

**Closed by ia0** 2023-08-18 22:10 UTC
