### ISSUE TITLE
Valid TOML is considered invalid with certain file extensions

### ISSUE THREAD

**Issue by Margen67** [tamasfe/taplo#442] opened 2023-07-26 21:28 UTC
If the file has an extension of `.patch.toml` instead of just `.toml` it gives nonsensical errors:
![](https://github.com/tamasfe/taplo/assets/3462541/b89dd51e-9af5-4aae-8e32-50481084f22f)
![](https://github.com/tamasfe/taplo/assets/3462541/c72ad942-c877-4fd5-9199-e14993211fb3)

just .toml:
![image](https://github.com/tamasfe/taplo/assets/3462541/3ad2cb58-3b5b-4b07-901a-a9e0da713b4e)

**Comment by Margen67** [comment] 2023-08-08 14:47
> I am not able to reproduce. I created the following file named `test.patch.toml`:
> 
> ```toml
> # comment
> ```
> 
> And I don't get any error with neither taplo-lsp nor `taplo lint --default-schema-catalogs test.patch.toml`.
> 
> What is the exact content of your file? The first screenshot is not clear.

The file you made should've reproduced it. Could it be because I'm using VSCode preview?

**Comment by panekj** [comment] 2023-08-08 14:52
I can reproduce the issue and it's because schema is `JSONPatch`

**Comment by ia0** [comment] 2023-08-08 14:59
Ok, then this is probably because you're using version 0.19.0 or 0.19.2. This should have been fixed in 0.19.1. See #426 for the fix and #434 for why VSCode can't have the fix yet. But if you don't experience crashes with 0.19.1, then that's the preferred version.

**Comment by Margen67** [comment] 2023-08-10 15:32
0.19.1 doesn't have this issue.

**Closed** 2023-08-10 15:46 UTC
Labels: vscode
