### ISSUE TITLE
Removing comments in arrays after formatting

### ISSUE THREAD

**Issue by ralpha** [tamasfe/taplo#198] opened 2021-12-17 14:32 UTC
When formatting my toml file it removed comments from an array.

Before:
```toml
deny = [
    #"Nokia",
]
```
After:
```toml
deny = []
```
This is not what I want to happen.

This issue might be related to: https://github.com/tamasfe/taplo/issues/182
But that issue shows a different behavior.

Maybe a good target for testing would be the default template for `cargo deny` https://github.com/EmbarkStudios/cargo-deny/blob/main/deny.template.toml

**Comment by tamasfe** [comment] 2021-12-18 07:40
Duplicate of #157, it's fixed in yet unpublished versions.

CD seems to be currently broken and I haven't got to investigate it yet, hopefully I'll find the time next weekend, sorry about the inconvenience.

**Closed by tamasfe** 2021-12-18 07:40 UTC

**Comment by ralpha** [comment] 2021-12-20 19:51
No problem, take your time. Library and plugin both seem very promising so will use it more over time when the bugs are ironed out.
Keep up the good work :smiley:
