### ISSUE TITLE
Schemas seem to get cached forever

### ISSUE THREAD

**Issue by abrahammurciano** [tamasfe/taplo#501] opened 2023-11-02 15:04 UTC
I have a TOML file starting with
```toml
#:schema /path/to/schema.schema.json
```
I frequently update the schema, but the extension doesn't detect the changes. The TOML is valid according to the new schema but it still complains with errors from the old schema. To make sure I made a copy of the schema and updated the comment, and it validated perfectly.

I tried reloading the window, reinstalling the extension, but none of that helped. I assume the extension must be caching it somewhere. I even tried setting `"evenBetterToml.schema.cache.diskExpiration": 1` and `"evenBetterToml.schema.cache.memoryExpiration": 1` in my settings.json but it had no effect.

Any help would be appreciated.

**Comment by ia0** [comment] 2023-11-03 16:21
Thanks for the report! This looks like a duplicate of #347.

**Closed by ia0** 2023-11-03 16:21 UTC
