### ISSUE TITLE
Package Taplo for installation with Homebrew

### ISSUE THREAD

**Issue by Jarmos-san** [tamasfe/taplo#262] opened 2022-06-09 15:47 UTC
Hi, thanks for the project!

I'm not a Rust dev & suffice to say, I don't have `cargo` & related dependencies installed on my machine but I want to use `taplo`. For now I download all (well almost all to be honest) using [Homebrew](https://brew.sh) so it would be nice to be able to `brew install taplo` as well!

I was wondering if it's possible to package `taplo` for Homebrew? If you think it's possible, here're the [relevant docs](https://docs.brew.sh/Formula-Cookbook) to get started with packaging the project.

**Comment by tamasfe** [comment] 2022-06-09 18:27
Hi, thanks for the suggestion, this is a duplicate of #251. As I mentioned there as well, I won't stop anyone packaging `taplo` but it's way out of scope for me personally.

**Closed by tamasfe** 2022-06-09 18:27 UTC
