### ISSUE TITLE
If the file name ends with ".test.toml", syntax highlighting will report errors.

### ISSUE THREAD

**Issue by lhyzf** [tamasfe/taplo#578] opened 2024-03-14 11:04 UTC
![image](https://github.com/tamasfe/taplo/assets/22554459/48fff756-ee56-4a27-bdde-16fd71930a1c)

**Comment by JounQin** [comment] 2024-03-14 11:08
Duplicate of #569

**Closed by JounQin** 2024-03-14 11:08 UTC
