### ISSUE TITLE
Reorder elements inside arrays

### ISSUE THREAD

**Issue by xamgore** [tamasfe/taplo#338] opened 2022-10-22 17:49 UTC
Hi! I would like to implement a PR that would allow sorting arrays. How I expect it to work:

```toml
# before
teloxide = { version = "0.11", features = ["macros", "auto-send", "rocksdb-storage"] }

# after
teloxide = { version = "0.11", features = ["auto-send", "macros", "rocksdb-storage"] }
```

What do you think about the idea? Are you ready to help me?

**Comment by tamasfe** [comment] 2022-10-24 19:22
Hi, thanks! This is a duplicate of #158, and the feature is welcome! I will close this in favour of the other issue.

> Are you ready to help me?

Yes, I will try, although in very limited ways.

The array formatting code can be found [here](https://github.com/tamasfe/taplo/blob/ce8e4fff753ccfcb2eb2875ab75323bd869ef655/crates/taplo/src/formatter/mod.rs#L923).

The code collects the values into groups that are separated by blank lines, so in theory sorting the rows before `format_rows` is called should get what you are looking for. The only issue is that at that point we only know about the formatted text, and we lose all other information, such as whether a value is a string or an integer, but I think a naive implementation could suffice.

So going by that implementation the sorting of multi-line arrays would look something like this:

```toml
# unformatted
foo = [
  "b",
  "a",
  "c",

  3,
  1,
  2,
]

# formatted
foo = [
  "a",
  "b",
  "c",

  1,
  2,
  3,
]
```

If we want absolute order without the groupings, this will get a bit more complicated.

After the formatting code is implemented, following are needed:
- add an option for it in the formatter options
- add tests for it
- documentation on the website
- add a vscode extension setting in `package.json`

**Closed** 2022-10-24 23:48 UTC
