### ISSUE TITLE
pyproject.toml's flake8 table is throwing "Additional properties are not allowed"

### ISSUE THREAD

**Issue by alfawal** [tamasfe/taplo#444] opened 2023-07-29 09:57 UTC
I've migrated from Better TOML to this extension. The first thing that I noticed was this error:
`Additional properties are not allowed` in my `pyproject.toml`.

The table:
```toml
[flake8]
max-line-length = 120
```

Screenshot:

<img width="729" alt="Screenshot 2023-07-29 at 12 45 07" src="https://github.com/tamasfe/taplo/assets/61620817/cbdc6e18-5961-4574-8774-54c9ae3912d5">

**Comment by ia0** [comment] 2023-08-08 14:13
This looks related to #316. Did you try using version 0.19.1?

**Comment by ia0** [comment] 2023-08-08 14:17
This may also be another issue with the schema, in which case it should be reported to https://github.com/SchemaStore/schemastore/issues.

**Comment by liamwazherealso** [comment] 2023-08-11 15:14
Seconded

```toml
[project]
name = "unify_dagster"
dynamic = ["version", "readme"]
dependencies = [
    "dagster",
    "pandas",
    "numpy",
    "scipy",
    "dagster-gcp",
    "plotnine",
    "responses",
    "requests",
    "html5lib",
]

[dev-dependencies]
"dagit" = "*"
"pytest" = "*"
```

Results in `Additional properties are not allowed ('dev-dependencies' was unexpected)`.

**Comment by gfgafn** [comment] 2023-08-11 19:11
> I've migrated from Better TOML to this extension. The first thing that I noticed was this error: `Additional properties are not allowed` in my `pyproject.toml`.
> 
> The table:
> 
> ```toml
> [flake8]
> max-line-length = 120
> ```
> 
> Screenshot:
> 
> <img alt="Screenshot 2023-07-29 at 12 45 07" width="729" src="https://user-images.githubusercontent.com/61620817/256976401-cbdc6e18-5961-4574-8774-54c9ae3912d5.png">


> [Flake8] cannot be configured via `pyproject.toml`
https://github.com/john-hen/Flake8-pyproject/blob/f8a71d8acc551143133a83d7bcf1598efd255d7f/ReadMe.md?plain=1#L4-L9

If you use https://github.com/john-hen/Flake8-pyproject to support use Flake8 in pyproject.toml, you should change it to 
```toml
[tool.flake8]
max-line-length = 120
```
see more from https://github.com/john-hen/Flake8-pyproject/blob/f8a71d8acc551143133a83d7bcf1598efd255d7f/ReadMe.md?plain=1#L25-L64

**Comment by gfgafn** [comment] 2023-08-11 19:20
> Seconded
> 
> ```toml
> [project]
> name = "unify_dagster"
> dynamic = ["version", "readme"]
> dependencies = [
>     "dagster",
>     "pandas",
>     "numpy",
>     "scipy",
>     "dagster-gcp",
>     "plotnine",
>     "responses",
>     "requests",
>     "html5lib",
> ]
> 
> [dev-dependencies]
> "dagit" = "*"
> "pytest" = "*"
> ```
> 
> Results in `Additional properties are not allowed ('dev-dependencies' was unexpected)`.

`dev-dependencies` is not a valid property according to [PEP518](https://peps.python.org/pep-0518/) and [PEP621](https://peps.python.org/pep-0621/)

**Comment by liamwazherealso** [comment] 2023-08-13 04:07
Gotcha, thanks

**Comment by ia0** [comment] 2023-08-13 08:44
Thanks for your help @gfgafn! Closing as working as intended.

**Closed by ia0** 2023-08-13 08:44 UTC
Labels: schema, needs investigation
