### ISSUE TITLE
Publish musllinux wheels

### ISSUE THREAD

**Issue by sanmai-NL** [tamasfe/taplo#701] opened 2024-11-15 12:30 UTC
I need a `musllinux_1_2_aarch64` wheel. More generally, people e.g., building Alpine Linux based container images, need `musllinux` wheels. On [PyPI: `taplo`](https://pypi.org/project/taplo/#files) no such wheels have been published.

**Comment by panekj** [comment] 2024-11-18 09:07
Duplicate of https://github.com/tamasfe/taplo/issues/658

**Closed by panekj** 2024-11-18 09:07 UTC

**Comment by sanmai-NL** [comment] 2024-11-18 09:35
Alpine Linux doesn't correspond to musllinux per se, but it's good to go back to that issue.
